@url = localhost:7070/api

### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
GET {{url}}/candidates/populate/

### Retrieve a candiadte based on a category
GET {{url}}/candidates/filter?category=PROG_LANG

### Create a candiadate
POST {{url}}/candidates/

{
    "name": "Oracle",

    "phone": "any",

    "education": "all",

    "skills":
    [
        {
    "name": "Knowlegde",
    "slug": "knowlegde",
    "category": "FRAMEWORK",
    "description": "She knows EVERYTHING"
        }
    ]
}

### Retrieve all candidates
GET {{url}}/candidates/

### Retrieve a candidate by ID
GET {{url}}/candidates/1/

### Update a candidate by ID
PATCH {{url}}/candidates/1/

{
    "name": "Oracle",

    "phone": "any",

    "education": "all",

    "skills":
    [
        {
    "name": "Knowlegde",
    "slug": "knowlegde",
    "category": "FRAMEWORK",
    "description": "She knows EVERYTHING"
        }
    ]
}

### Add skill (skid_id=2) on a candidate (candidate_id=1)
PATCH {{url}}/candidates/1/skills/2/

### Delete a candidate by ID
DELETE {{url}}/candidates/1/

### Retrieve a skill (with id) by a candidate (with id)
GET {{url}}/candidates/1/skills/1/

### Retrieve a all skills (with id) associated to a candidate (by id)
GET {{url}}/candidates/1/skills/


###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}
